// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB60aBd8NNziQByyqQY-s-5S8qqhPv7pC0',
    appId: '1:921846174509:web:4b3db47fea384cb48a79a4',
    messagingSenderId: '921846174509',
    projectId: 'inappwebview-b3e0e',
    authDomain: 'inappwebview-b3e0e.firebaseapp.com',
    storageBucket: 'inappwebview-b3e0e.appspot.com',
    measurementId: 'G-W7FLYSRXMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfLcKyywCbpiyZrc2ydVpDqMtgv8isQAE',
    appId: '1:921846174509:android:94e347926b6f22658a79a4',
    messagingSenderId: '921846174509',
    projectId: 'inappwebview-b3e0e',
    storageBucket: 'inappwebview-b3e0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjxS5x0TfCK2W-KQWHrOfLnTj2Gc_Z5Tc',
    appId: '1:921846174509:ios:cade12513fe9aa268a79a4',
    messagingSenderId: '921846174509',
    projectId: 'inappwebview-b3e0e',
    storageBucket: 'inappwebview-b3e0e.appspot.com',
    iosBundleId: 'com.example.webviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjxS5x0TfCK2W-KQWHrOfLnTj2Gc_Z5Tc',
    appId: '1:921846174509:ios:cade12513fe9aa268a79a4',
    messagingSenderId: '921846174509',
    projectId: 'inappwebview-b3e0e',
    storageBucket: 'inappwebview-b3e0e.appspot.com',
    iosBundleId: 'com.example.webviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB60aBd8NNziQByyqQY-s-5S8qqhPv7pC0',
    appId: '1:921846174509:web:76de51b8cafc5fcb8a79a4',
    messagingSenderId: '921846174509',
    projectId: 'inappwebview-b3e0e',
    authDomain: 'inappwebview-b3e0e.firebaseapp.com',
    storageBucket: 'inappwebview-b3e0e.appspot.com',
    measurementId: 'G-ZNGXJG5HV9',
  );
}
